spring.application.name=cinema-booking-app

spring.datasource.url=jdbc:mysql://localhost:3306/cinema_booking_db?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

cinewave.security.remember-me.key=${CINEWAVE_REMEMBER_ME_KEY:default-dev-secret-key-cinewave}